import type { LanguageMode, RenderedFile, RepositoryReport, RiskSignal } from "./types.js";

const marker = "<!-- Generated by AgentBriefcase. Edit with care. -->";

export function renderFiles(report: RepositoryReport, language: LanguageMode): RenderedFile[] {
  const files: RenderedFile[] = [];

  if (language === "en" || language === "both") {
    files.push({ path: "AGENTS.md", content: renderAgents(report, "en", language) });
  }

  if (language === "zh-CN") {
    files.push({ path: "AGENTS.md", content: renderAgents(report, "zh-CN", language) });
  }

  if (language === "both") {
    files.push({ path: ".agentbriefcase/AGENTS.zh-CN.md", content: renderAgents(report, "zh-CN", language) });
  }

  if (language === "en" || language === "both") {
    files.push({ path: ".agentbriefcase/context.md", content: renderContext(report, "en") });
  }
  if (language === "zh-CN" || language === "both") {
    files.push({
      path: language === "zh-CN" ? ".agentbriefcase/context.md" : ".agentbriefcase/context.zh-CN.md",
      content: renderContext(report, "zh-CN")
    });
  }

  if (language === "en" || language === "both") {
    files.push({ path: ".agentbriefcase/checks.md", content: renderChecks(report, "en") });
  }
  if (language === "zh-CN" || language === "both") {
    files.push({
      path: language === "zh-CN" ? ".agentbriefcase/checks.md" : ".agentbriefcase/checks.zh-CN.md",
      content: renderChecks(report, "zh-CN")
    });
  }

  if (language === "en" || language === "both") {
    files.push({ path: ".agentbriefcase/risks.md", content: renderRisks(report, "en") });
  }
  if (language === "zh-CN" || language === "both") {
    files.push({
      path: language === "zh-CN" ? ".agentbriefcase/risks.md" : ".agentbriefcase/risks.zh-CN.md",
      content: renderRisks(report, "zh-CN")
    });
  }

  files.push({ path: ".agentbriefcase/manifest.json", content: `${JSON.stringify(report, null, 2)}\n` });

  return files;
}

function renderAgents(report: RepositoryReport, lang: "en" | "zh-CN", mode: LanguageMode): string {
  if (lang === "zh-CN") {
    const switcher =
      mode === "both" ? "语言：[English](../AGENTS.md) | [中文](AGENTS.zh-CN.md)" : "语言：中文";
    return lines([
      marker,
      "# Agent 简报箱",
      switcher,
      "",
      `项目：${report.name}`,
      `生成时间：${report.generatedAt}`,
      "",
      "## 开始前请读",
      "- 优先阅读 `.agentbriefcase/context.md` 或对应中文文件，了解仓库形态。",
      "- 修改前先查看 `.agentbriefcase/checks.md`，选择最小可验证命令。",
      "- 若 `.agentbriefcase/risks.md` 中有高风险项，先处理或向维护者确认。",
      "- 不要把真实密钥、令牌或私有日志粘贴给 AI。",
      "",
      "## 快速事实",
      listFacts(report, "zh-CN"),
      "",
      "## 推荐验证命令",
      renderCommandList(report, "zh-CN")
    ]);
  }

  const switcher =
    mode === "both" ? "Language: [English](AGENTS.md) | [中文](.agentbriefcase/AGENTS.zh-CN.md)" : "Language: English";
  return lines([
    marker,
    "# Agent Briefcase",
    switcher,
    "",
    `Project: ${report.name}`,
    `Generated: ${report.generatedAt}`,
    "",
    "## Read This First",
    "- Start with `.agentbriefcase/context.md` to understand the repository shape.",
    "- Before editing, open `.agentbriefcase/checks.md` and pick the smallest useful verification command.",
    "- If `.agentbriefcase/risks.md` lists high-severity items, handle them or ask the maintainer first.",
    "- Never paste real secrets, tokens, or private logs into AI chats.",
    "",
    "## Quick Facts",
    listFacts(report, "en"),
    "",
    "## Recommended Checks",
    renderCommandList(report, "en")
  ]);
}

function renderContext(report: RepositoryReport, lang: "en" | "zh-CN"): string {
  if (lang === "zh-CN") {
    return lines([
      marker,
      "# 仓库上下文",
      "",
      "## 仓库形态",
      listFacts(report, "zh-CN"),
      "",
      "## 关键文件",
      bulletList(report.keyFiles, "未检测到关键文件。"),
      "",
      "## 文件概览",
      bulletList(report.files.slice(0, 50).map((file) => `${file.path} (${formatBytes(file.size)})`), "未检测到文件。")
    ]);
  }

  return lines([
    marker,
    "# Repository Context",
    "",
    "## Repository Shape",
    listFacts(report, "en"),
    "",
    "## Key Files",
    bulletList(report.keyFiles, "No key files detected."),
    "",
    "## File Overview",
    bulletList(report.files.slice(0, 50).map((file) => `${file.path} (${formatBytes(file.size)})`), "No files detected.")
  ]);
}

function renderChecks(report: RepositoryReport, lang: "en" | "zh-CN"): string {
  if (lang === "zh-CN") {
    return lines([
      marker,
      "# 验证命令",
      "",
      "按最小必要原则运行命令。优先运行与你修改范围最相关的检查。",
      "",
      renderCommandList(report, "zh-CN")
    ]);
  }

  return lines([
    marker,
    "# Verification Checks",
    "",
    "Run the smallest command that verifies the change you made.",
    "",
    renderCommandList(report, "en")
  ]);
}

function renderRisks(report: RepositoryReport, lang: "en" | "zh-CN"): string {
  if (lang === "zh-CN") {
    return lines([marker, "# 风险信号", "", renderRiskList(report.risks, "zh-CN")]);
  }

  return lines([marker, "# Risk Signals", "", renderRiskList(report.risks, "en")]);
}

function listFacts(report: RepositoryReport, lang: "en" | "zh-CN"): string {
  if (lang === "zh-CN") {
    return bulletList([
      `语言：${joinOrFallback(report.languages, "未检测到")}`,
      `框架：${joinOrFallback(report.frameworks, "未检测到")}`,
      `包管理器：${joinOrFallback(report.packageManagers, "未检测到")}`,
      `文件数：${report.files.length}`
    ]);
  }

  return bulletList([
    `Languages: ${joinOrFallback(report.languages, "none detected")}`,
    `Frameworks: ${joinOrFallback(report.frameworks, "none detected")}`,
    `Package managers: ${joinOrFallback(report.packageManagers, "none detected")}`,
    `Files scanned: ${report.files.length}`
  ]);
}

function renderCommandList(report: RepositoryReport, lang: "en" | "zh-CN"): string {
  if (report.commands.length === 0) {
    return lang === "zh-CN" ? "未检测到明确命令。请查看项目 README 或询问维护者。\n" : "No clear commands detected. Check the project README or ask a maintainer.\n";
  }

  return report.commands
    .map((command) => `- ${command.name} (${command.confidence}): \`${command.command}\``)
    .join("\n");
}

function renderRiskList(risks: RiskSignal[], lang: "en" | "zh-CN"): string {
  if (risks.length === 0) {
    return lang === "zh-CN" ? "未检测到明显风险。\n" : "No obvious risks detected.\n";
  }

  return risks.map((risk) => `- [${risk.severity}] ${risk.title}: ${risk.detail}`).join("\n");
}

function bulletList(items: string[], fallback = "None."): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : fallback;
}

function joinOrFallback(items: string[], fallback: string): string {
  return items.length > 0 ? items.join(", ") : fallback;
}

function formatBytes(size: number): string {
  if (size < 1024) return `${size} B`;
  if (size < 1024 * 1024) return `${(size / 1024).toFixed(1)} KB`;
  return `${(size / 1024 / 1024).toFixed(1)} MB`;
}

function lines(parts: string[]): string {
  return `${parts.join("\n")}\n`;
}
